# Generated by Django 5.2.2 on 2025-06-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchainproject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="private_key",
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
